version: "1"

code: "240001"

broker:
  type: "v2"
  url: "http://localhost:1026"
  service: "covid19"
  path: "/"

aggregate:
  - "TestPeopleDaily"
  - "TestCountDaily"
  - "ConfirmNegativeDaily"
  - "CallCenterDaily"
  - "PatientsDaily"
  - "PatientsList"
  - "PatientsSummary"
