version: "3"
services:

  covid19:
    container_name: covid19
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: fiware-covid19/covid19
    tty: true
    environment:
      - NUXT_ENV_MUNICIPALITY_CODE=$CODE
      - NUXT_ENV_BROKER_SERVICE=covid19
      - NUXT_ENV_BROKER_PATH=/
    volumes:
      - node_modules:/app/node_modules

  orion:
    container_name: orion
    image: fiware/orion:2.5.2
    depends_on:
      - mongo
    ports:
      - "1026:1026"
    command: -dbhost mongo -inReqPayloadMaxSize 10MB

  mongo:
    container_name: mongo
    image: mongo:3.6
    command: --nojournal
    volumes:
      - ./data/v2/db:/data/db
      - ./data/v2/conf:/data/configdb

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "3000:80"
    depends_on:
      - covid19
      - orion
    volumes:
      - ./v2.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  node_modules: {}
