version: "3"
services:

  covid19:
    container_name: covid19
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: fiware-covid19/covid19
    tty: true
    environment:
      - NUXT_ENV_MUNICIPALITY_CODE=$CODE
      - NUXT_ENV_BROKER_VERSION=ld
      - NUXT_ENV_BROKER_SERVICE=covid19
      - NUXT_ENV_BROKER_CONTEXT=https://cio-context.fiware-testbed.jp/cio-context-en.jsonld
    volumes:
      - node_modules:/app/node_modules

  orionld:
    container_name: orionld
    image:  fiware/orion-ld:0.6.1
    depends_on:
      - mongo
    ports:
      - "1026:1026"
    command: -dbhost mongo

  mongo:
    container_name: mongo
    image: mongo:3.6
    command: --nojournal
    volumes:
      - ./data-ld/db:/data/db
      - ./data-ld/conf:/data/configdb

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "3000:80"
    depends_on:
      - covid19
      - orionld
    volumes:
      - ./ld.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  node_modules: {}
